package io.naman.masterpass.demo.controller;


import com.mastercard.merchant.checkout.PaymentDataApi;
import com.mastercard.merchant.checkout.model.Address;
import com.mastercard.merchant.checkout.model.PaymentData;
import com.mastercard.sdk.core.util.QueryParams;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Created by e057964 on 26/9/17.
 */

@Controller
public class WebController extends BaseController {

    @Value("${masterpass.merchant.checkoutId}")
    String merchantCheckoutId;

    @Value("${masterpass.merchant.callbackUrl}")
    String callBackUrl;

    @RequestMapping("/")
    ModelAndView home(HttpSession httpSession) {

        ModelAndView mv = new ModelAndView("home");
        return mv;
    }


    @RequestMapping("/checkout")
    String checkout(@RequestParam("mpstatus") String status, @RequestParam(value = "oauth_token", required = false) String oauthToken,
                          @RequestParam(value = "oauth_verifier", required = false) String oauthVerifier,
                          @RequestParam(value = "checkout_resource_url", required = false) String checkoutResourceUrl, HttpSession httpSession) {

        if(status.equals("success")){

            httpSession.setAttribute("oauth_verifier",oauthVerifier);
        }

        return "redirect:/success";
    }

    @RequestMapping("/standardCheckout")
    ModelAndView standardCheckout(HttpSession httpSession) {

        ModelAndView mv = new ModelAndView("standardCheckout");

        //Generate random cartID
        String cartId = UUID.randomUUID().toString();

        httpSession.setAttribute("cart_id",cartId);


        mv.addObject("cart_id",cartId);
        mv.addObject("checkout_id",merchantCheckoutId);
        mv.addObject("callback_url",callBackUrl);

        return mv;


    }

    @RequestMapping("/success")
    ModelAndView success(HttpSession httpSession) {

        ModelAndView mv = new ModelAndView("success");
        mv.addObject("transactionId",httpSession.getAttribute("oauth_verifier"));

        //Step 7
        QueryParams queryParams = new QueryParams()
                .add("checkoutId", merchantCheckoutId) //Checkout ID that you received from Merchant Portal
                .add("cartId", httpSession.getAttribute("cart_id").toString()); // CartID generated by you and should be same as passed in step 3

        PaymentData paymentData = PaymentDataApi.show(httpSession.getAttribute("oauth_verifier").toString(), queryParams);
        System.out.println("Card number is "+paymentData.getCard().getAccountNumber());
        Address shippingAdd = paymentData.getShippingAddress();

        List<String> shippingAddress = new ArrayList<>();

        if(shippingAdd != null){

            if(shippingAdd.getLine1() != null){

                shippingAddress.add(shippingAdd.getLine1());

            }
            if(shippingAdd.getLine2() != null){

                shippingAddress.add(shippingAdd.getLine2());

            }
            if(shippingAdd.getLine3() != null){

                shippingAddress.add(shippingAdd.getLine3());

            }

            if(shippingAdd.getCity() != null){

                shippingAddress.add(shippingAdd.getCity());


            }

            if(shippingAdd.getCountry() != null){

                shippingAddress.add(shippingAdd.getCountry());
            }

            if(shippingAdd.getPostalCode()!=null){
                shippingAddress.add(shippingAdd.getPostalCode());
            }

        }

        mv.addObject("shippingAddress",shippingAddress);

        return mv;
    }
}
